plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

supportedArchitectures:
  cpu:
    - x64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.2.2.cjs
